# Generated by Django 2.1.5 on 2020-08-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='客户名称')),
                ('phonenumber', models.CharField(max_length=200, verbose_name='联系电话')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
            ],
        ),
    ]
